### ISSUE TITLE
API_KEY and FQDN

### ISSUE THREAD

**Issue by itssubas** [fvigo/soarhelloworld#2]
Hi,
Can you please explain what value should we use in API_KEY and FQDN in `secrets.yml`?

**Comment by fvigo** [comment]
@itssubas those should contain the API KEY you want the API you deploy to accept for incoming requests, and the FQDN you want to deploy your API to respond to (needs to be in route53)

**Comment by itssubas** [comment]
Thank you @fvigo. 

FQDN should be the domain name of that XSOAR instance/service for which our deployed API would respond?

**Comment by fvigo** [comment]
@itssubas correct

**Comment by fvigo** [comment]
no sorry I misunderstood your question.

This API is deployed in AWS and will respond to this FQDN configured in Cloudfront.

This FQDN is what you will configure in the HelloWorld XSOAR instance when you want XSOAR to connect to this API

**Comment by fvigo** [comment]
no sorry I misunderstood your question.

This API is deployed in AWS and will respond to this FQDN configured in Cloudfront.

This FQDN is what you will configure in the HelloWorld XSOAR instance when you want XSOAR to connect to this API

**Comment by fvigo** [comment]
@itssubas if you have more questions please connect to me on the Slack DFIR workspace (my handle is fv)
